### ISSUE TITLE
Windows users cannot run Liferay server via Blade

### ISSUE THREAD

**Issue by codyhoag** [gamerson/liferay-blade-tools#110]
When I run the following command:

    blade server -b

I am given an error message specifying that I "Cannot run program "sh" ". When switching to a command prompt that supports shell scripts (e.g., Cygwin), I'm able to run the server. Windows support should be included when running a Liferay server from Blade tools.

**Comment by david-truong** [comment]
I'm getting the same issue with blade gw.  Will take a look thanks

**Comment by david-truong** [comment]
fixed in 8d099e5
