### ISSUE TITLE
Blade "update" command doesn't work on Windows

### ISSUE THREAD

**Issue by codyhoag** [gamerson/liferay-blade-tools#119]
When running `blade update` from a Windows machine, the following error is returned:
```
Error
  0. [FileOutputStream.open] E:\JPM4J\bin\blade.exe (The process cannot access the file because it is being used by another process)
Error
  0. blade exited with code: 1
```
This is because Windows can't update a file that is running.

**Comment by gamerson** [comment]
@david-truong for windows can we just print out the command to the console that developers need to use to update on windows?  ```jpm install -f ...``` ?

**Comment by gamerson** [comment]
moved to here: https://github.com/gamerson/liferay-blade-cli/issues/8
