### ISSUE TITLE
com.liferay.blade.test.InitJSPParseTest is failling

### ISSUE THREAD

**Issue by gamerson** [gamerson/liferay-blade-tools#123]

**Comment by gamerson** [comment]
@lovettli can you take a look?

**Comment by lovettli** [comment]
OK. i will check it.

**Comment by lovettli** [comment]
Hey Greg, i test it use latest code and reset to the code before submit to ignore. no fail. Can you send me some error log?

**Comment by gamerson** [comment]
Let me check something again now that I have switched the pull request
tester to cloudbees.

On Tue, Feb 16, 2016 at 12:16 AM, Lovett Li <notifications@github.com>
wrote:

> Hey Greg, i test it use latest code and reset to the code before submit to
> ignore. no fail. Can you send me some error log?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-blade-tools/issues/123#issuecomment-184535955>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by lovettli** [comment]
Hey Greg, I think this ticket is done, can we close it ?

**Comment by gamerson** [comment]
yes!

On Wed, Feb 24, 2016 at 7:31 PM, Lovett Li <notifications@github.com> wrote:

> Hey Greg, I think this ticket is done, can we close it ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-blade-tools/issues/123#issuecomment-188549888>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com
