### ISSUE TITLE
[migrator] Removed the aui:button-item Tag and Replaced with aui:button

### ISSUE THREAD

**Issue by lovettli** [gamerson/liferay-blade-tools#145]
Date: 2016-Feb-04
https://issues.liferay.com/browse/LPS-62922
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-the-auibutton-item-tag-and-replaced-with-auibutton

type:jsp

**Comment by gamerson** [comment]
Moved to here: https://github.com/gamerson/liferay-blade-cli/issues/7
