### ISSUE TITLE
service builder template created in workspace contains settings.gradle

### ISSUE THREAD

**Issue by david-truong** [gamerson/liferay-blade-tools#153]
settings.gradle should never be included anywhere but the root project

**Comment by david-truong** [comment]
https://github.com/gamerson/liferay-blade-tools/pull/156

**Comment by AndyWu2015** [comment]
almost the same time .... I sent the pr .. :)

**Comment by lovettli** [comment]
@david-truong How about our servicebuilder template settings.gradle file which contains include project configuration? rename it or move include configuration.

**Comment by david-truong** [comment]
We only need to remove it for workspace builds which will automatically
include projects.  Don’t need to rename it or move include configurations

**Comment by gamerson** [comment]
@david-truong is this fixed now?

**Comment by david-truong** [comment]
should be ;-)

**Comment by gamerson** [comment]
do we have a unit test for it?

**Comment by david-truong** [comment]
Yep
