### ISSUE TITLE
Need to update servicebuilder blade tools template due to servicebuilder module update

### ISSUE THREAD

**Issue by jrao** [gamerson/liferay-blade-tools#17]
When you create a new servicebuilder project and run buildService, the following method is generated in the API module's FooLocalServiceWrapper class:

	@Override
	public com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		return _fooLocalService.getIndexableActionableDynamicQuery();
	}

This creates a compilation error since com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery is not on the classpath. I didn't run into this issue yesterday so I'm assuming it's due to a recent service builder module update. I checked the blade.servicebuilder.svc project and running buildService there produces the same error.

**Comment by jrao** [comment]
Hey @AndyWu2015 , Greg suggested that you could take a look at this issue. Thanks!

**Comment by AndyWu2015** [comment]
Of couse !  Jesse

**Comment by AndyWu2015** [comment]
Got the same error.
I found the IndexableActionableDynamicQuery class was added 4 day ago (2015-11-19) and the latest  portal-service-7.0.0-20151106.003905-1958.jar date is 2015-11-06 without that class , so I guess that they built it with some delay . And I don't know which one is in charge of building it . So you may can help to remind this . :)  thanks !

**Comment by jrao** [comment]
@sez11a, Hey Rich, Andy found that this issue is likely due to the fact that the portal-service.jar on Liferay's repository is simply out of date. Do you know who's in charge of updating it or who we should contact about this?

**Comment by sez11a** [comment]
@jrao @jhinkey No, I have no idea. Jim, do you?

**Comment by jhinkey** [comment]
@jrao I don't know. I think it would be Andrea. On the #build channel, I would tag Andrea, explain that the JAR is out of date, and ask if he can update it or could tell you who updates it.
/cc @sez11a

**Comment by AndyWu2015** [comment]
Any update news ? @jhinkey

**Comment by jhinkey** [comment]
@AndyWu2015 , @jrao - Can you guys tell me where in the repo you're looking for the portal-service*.jar?

Chas (@CAustin582) - From where should we be getting the latest portal-service JAR? Can you make sure the latest is posted to the repo and let us know it's URL? Thanks!

**Comment by AndyWu2015** [comment]
here @jhinkey https://repository.liferay.com/nexus/content/repositories/liferay-ce/com/liferay/portal/portal-service/7.0.0-SNAPSHOT/

**Comment by CAustin582** [comment]
Hey guys, if you want to guarantee that you're getting the most up-to-date portal-service.jar, building from source is currently the only way to go. The 7.0.0 snapshot jars are by no means an official release that should be relied upon. It's good to see that people have found them useful in some situations, but they are mostly an experimental project that I set up a while back on the release server. The jars should be accurate representations of a maven release and safe to use, but the schedule on which they are published is subject to change or be halted altogether (they get built from the release server, which often needs to be used for lots of other important things).

I do plan on solidifying official snapshots that people can depend on (for the 6.* branches as well). Seeing this makes me realize that there's actually demand for it, which is great. Ideally I'll also be publishing constant module snapshots too. I'll post an update in the #build slack channel when this becomes a reality.

**Comment by AndyWu2015** [comment]
Thanks @CAustin582  , many developers are trying our liferay-blade-tools and they need latest jars when building samples . If we let them get the latest jars from building source , it will make them feel troublesome .

**Comment by CAustin582** [comment]
@AndyWu2015: Snapshots for 7.0.0 should now be getting published whenever new commits are seen on upstream. I moved the job to an alternative server so there won't be any conflicts with the normal release process. Note that 7.0.0-SNAPSHOT is generated from the master branch, not 7.0.x.

**Comment by AndyWu2015** [comment]
Thanks @CAustin582  , by the way , do we have any plans to publish our modules in portal into maven central repo when we get portal 7 released ?

**Comment by CAustin582** [comment]
Yes, part of our release process for 7.0 will involve publishing the modules to the repo some time before the final GA1 release. We're also planning to host them on marketplace.

**Comment by AndyWu2015** [comment]
thanks for your answer , really good news !

**Comment by AndyWu2015** [comment]
finished , close this

**Comment by gamerson** [comment]
Closing
