### ISSUE TITLE
support new service builder template that supports common scenario

### ISSUE THREAD

**Issue by gamerson** [gamerson/liferay-blade-tools#170]
so people will like to do something like this:
```
backend-integration  (root directory)
    backend-integration-api  (directory name and project name in eclipse)
    backend-integration-service  (directory name and project name in eclipse)
    backend-integration-web (directory name and project name in eclipse)
```
where each of the bundles has these packages
```
com.liferay.backend.integration.api  (both root package and BSN and bundle name)
com.liferay.backend.integration.service (both root package and BSN and bundle name)
com.liferay.backend.integration.web (both root package and BSN and bundle name)
```

**Comment by dnebing** [comment]
Do not use ".service" as a directory suffix, OSX interprets it as a special directory.

**Comment by gamerson** [comment]
Yes that is true but in this case the directory ends with -service.  So this should be ok right?

**Comment by dnebing** [comment]
I think a dash is okay for directory names.  Issue is that blade creates the submodules with a ".api", ".svc" and ".web" extension, the names are not user generated.

**Comment by gamerson** [comment]
Yes that is true, and that is what we were thinking about with this new
issue, is that we should support the '-' based directories, which is
Liferay defacto standard.  Its just the OSGi defacto standard (and eclipse
standard) is directories that are named like their internal root packages
(and final bundle names).

On Mon, Mar 14, 2016 at 10:11 AM, Dave Nebinger <notifications@github.com>
wrote:

> I think a dash is okay for directory names. Issue is that blade creates
> the submodules with a ".api", ".svc" and ".web" extension, the names are
> not user generated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-blade-tools/issues/170#issuecomment-196360865>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by dnebing** [comment]
Standards are good things and should probably be followed unless there is a compelling reason not to, IMHO.  Just wanting shorter project names would seem not to be very compelling.
