### ISSUE TITLE
blade sample command fails

### ISSUE THREAD

**Issue by planetsizebrain** [gamerson/liferay-blade-tools#191]
It seems the blade sample command currently fails, with a NullPointerException, because Ray's Blade Samples repo has moved and the old URL is still used in the _BLADE_REPO_URL constant in com.liferay.blade.cli.SamplesCommand. 

If I manually unzip a version of the correct repo in ${user.home}/.blade/cache/blade-master the command starts working again.

**Comment by gamerson** [comment]
hey @planetsizebrain thanks for the report.  We have moved the blade cli over to official repo too, https://github.com/liferay/liferay-blade-cli

also we have published our 1.0.0 release of blade cli and it can be installed with jpm proper

```
$ sudo jpm install com.liferay.blade.cli
```

With this version the _BLADE_REPO_URL has been property updated, see here:  https://github.com/liferay/liferay-blade-cli/blob/master/com.liferay.blade.cli/src/com/liferay/blade/cli/SamplesCommand.java#L233

I'm going to be deprecating this repo today to forward everyone over to the new repo which contains new installation instructions.
