### ISSUE TITLE
[migrator] Moved Recycle Bin logic into a new DLTrashService interface

### ISSUE THREAD

**Issue by lovettli** [gamerson/liferay-blade-tools#27]
Date: 2015-Dec-02
https://issues.liferay.com/browse/LPS-60810
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#moved-recycle-bin-logic-into-a-new-dltrashservice-interface

type:java

**Comment by gamerson** [comment]
moved to https://github.com/gamerson/liferay-blade-cli/issues/10
