### ISSUE TITLE
Fetched workspace directory in the "com.liferay.workspace" plugin ("samples/" in sources-jar) has no Gradle Wrapper files  

### ISSUE THREAD

**Issue by sustacek** [gamerson/liferay-blade-tools#64]
This line relies on `gradlew` file being present in the sample workspace:
* https://github.com/gamerson/liferay-blade-tools/blob/master/com.liferay.blade.cli/src/com/liferay/blade/cli/InitCommand.java#L86

But there is no such file (or other, like `gradlew.bat`, `gradle/wrapper/...`) in `samples/`:
* https://github.com/liferay/liferay-portal/tree/master/modules/sdk/gradle-plugins-workspace/samples

Should the samples/ contain Gradle Wrapper?

**Comment by gamerson** [comment]
@sustacek yes we need to include gradle wrapper in the samples.

**Comment by sustacek** [comment]
@gamerson okay, I was just wondering what is the plan. I want to test the workspace to be able to add our GS scripts.

**Comment by gamerson** [comment]
This should be fixed here: https://github.com/Ithildir/liferay-portal/pull/183
cc @david-truong 

We can leave this open until that gets merged.

**Comment by sustacek** [comment]
@gamerson great, thanks for update!

**Comment by gamerson** [comment]
Fix has been merged.

**Comment by sustacek** [comment]
Thanks!
