### ISSUE TITLE
Blade Install agent command didn't support windows "\" in path.

### ISSUE THREAD

**Issue by simonjhy** [gamerson/liferay-blade-tools#67]
The blade  install agent command did't support user use windows style "\" in path in windows system. It only support "/".

**Comment by gamerson** [comment]
hey @simonjhy can you try to send a pull request to fix it?  thanks!

**Comment by gamerson** [comment]
@simonjhy  you mean if the user types in a "\" as the path in the argument?

**Comment by simonjhy** [comment]
greg, the path muste be as unix path, the "/" can be accept by blade

2016-02-04 6:15 GMT+08:00 Gregory Amerson <notifications@github.com>:

**Comment by gamerson** [comment]
this appears to be a problem with libg library as it is not expecting to see \ in the path names.  the fix would have to be there.

**Comment by david-truong** [comment]
Can’t we do a string replace before we pass it in?

On Thu, Feb 4, 2016 at 12:31 PM, Gregory Amerson <notifications@github.com>
wrote:

> this appears to be a problem with libg library as it is not expecting to
> see \ in the path names. the fix would have to be there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-blade-tools/issues/67#issuecomment-179985997>
> .
>



-- 
David Truong
Product Manager
david.truong@liferay.com
Liferay, Inc

**Comment by gamerson** [comment]
I "think"  that in an "Options" class if we specify that we have a "File" argument, the libg framework will convert that "C:\windows\have\backslashses" and try to coerce it into a "File" object by calling

new File(stringWithBackslashes) and that is failing

**Comment by gamerson** [comment]
so the fix would be in the libg framework here likely: https://github.com/bndtools/bnd/blob/master/aQute.libg/src/aQute/configurable/Configurable.java#L96

**Comment by gamerson** [comment]
we could send a pull

**Comment by gamerson** [comment]
@simonjhy can you tell us more exactly what is happening?  Can you debug blade jar and see if the agent install command is even getting invoked, if the failure is in our code or if it is in the libg code.  Also tell use exactly the string you are sending blade when it fails, thanks!

**Comment by simonjhy** [comment]
$ blade agent install -l D:\Liferay_Runtime\liferay-portal-7.0-ce-b3
Error
  0. agent: Could not find modules dir at D:\dev java\liferay-blade-tools\com.liferay.blade.cli\generated\Liferay_Runtimeliferay-portal-7.0-ce-b3\osgi\modules

liferay@LIFERAY-PC /d/dev java/liferay-blade-tools/com.liferay.blade.cli/generated (master)
$ blade agent install -l D:/Liferay_Runtime/liferay-portal-7.0-ce-b3
Installed remote agent sucessfully. Please wait 5-10 seconds for remote agent to be autodeployed, then use the "blade sh <gogo-command>". At any time, uninstall the remote agent by using the "blade agent uninstall" command.

**Comment by AndyWu2015** [comment]
hey guys, I got the error:
----------------------------------------------------------------------------
C:\Users\liferay>blade agent install -l d:/master20160107
Error
  0. [Macro.<clinit>] aQute/libg/cryptography/Digester
----------------------------------------------------------------------------
any ideas ?

**Comment by gamerson** [comment]
We need to include that package in blade jar.

On Friday, February 5, 2016, Andy Wu <notifications@github.com> wrote:

> hey guys, I got the error:
>
> C:\Users\liferay>blade agent install -l d:/master20160107
> Error
> 0. [Macro.] aQute/libg/cryptography/Digester
>
> any ideas ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-blade-tools/issues/67#issuecomment-180246960>
> .
>


-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
@AndyWu2015 do you have a windows machine that you could debug that line in the libg class?

**Comment by AndyWu2015** [comment]
I was trying to debug but it can't compile  , any ideas ?
![qq 20160215122431](https://cloud.githubusercontent.com/assets/12250744/13039822/2b4c3784-d3df-11e5-9e3b-ef7cb162b175.png)

**Comment by AndyWu2015** [comment]
yeah , @gamerson I've fix it and send the pr.

**Comment by gamerson** [comment]
So I guess you were able to import the new gradle project?  Did that fix it?

On Mon, Feb 15, 2016 at 1:26 AM, Andy Wu <notifications@github.com> wrote:

> yeah , @gamerson <https://github.com/gamerson> I've fix it and send the
> pr.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-blade-tools/issues/67#issuecomment-184095642>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
you mean the bug about downloading gradle dist in buildship ? I think not

**Comment by gamerson** [comment]
No this is a problem of "blade agent install" command didn't work on
windows.

On Mon, Feb 15, 2016 at 8:14 PM, Andy Wu <notifications@github.com> wrote:

> you mean the bug about downloading gradle dist in buildship ? I think not
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-blade-tools/issues/67#issuecomment-184476440>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
and now it works .

**Comment by gamerson** [comment]
AgentCommand is gone now.
