### ISSUE TITLE
blade create project build.gradle file's content not correct

### ISSUE THREAD

**Issue by oyangbingxi** [gamerson/liferay-blade-tools#82]
If users run "blade create test" in root of liferay-workspace folder not modules/apps folder , it will create simple build.gradle not standalone style

**Comment by AndyWu2015** [comment]
I think we should prompt user that they can't create projects in the root of liferay-workspace folder or any other folders which is not apps or extensions or shared in modules

**Comment by gamerson** [comment]
Yeah actually @david-truong did some work in this regards where new "modules" would automatically get added in "modules" and would have the correct "workspace" build.gradle templates.
