### ISSUE TITLE
The superclass "javax.servlet.http.HttpServlet" was not found on the Java Build Path

### ISSUE THREAD

**Issue by oyangbingxi** [gamerson/liferay-blade-tools#89]
1.create gradle mvcportlet project (in workspace or stand-alone) in IDE or import gradle project(created by cmd command) into IDE
2.then go to jsp file
on the first line it will show:
The superclass "javax.servlet.http.HttpServlet" was not found on the Java Build Path

**Comment by AndyWu2015** [comment]
I think it is because the lack of  the dependency of javax.servlet:servlet-api:2.5
